import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import CardBackground from '../components/CardBackground'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <div>
      <div className={styles.wallpaper}>
        <Nav />
        <div >
          <Head>
            <title>Nissan Store</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="Brand.png" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
          </Head>
          <main>
            <CardBackground />
          </main>
        </div>
      </div>
      <Footer />
    </div>
  )
}