import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import stylesStore from '../styles/Store.module.css'
import stylesCard from '../styles/Card.module.css'

import Nav from '../components/Nav'
import Footer from '../components/Footer'

import 'bootstrap/dist/css/bootstrap.min.css';
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import CardGroup from 'react-bootstrap/CardGroup'
import Card from 'react-bootstrap/Card'
import ListGroup from 'react-bootstrap/ListGroup'
import ListGroupItem from 'react-bootstrap/ListGroupItem'

import Spinner from 'react-bootstrap/Spinner'

export default function Store({ cars }) {
  return (
    <div className="contenedor">
      <div>
        <Head>
          <title>Nissan Store</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="Brand.png" />
          <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
        </Head>
        <Nav />
        <div className={stylesStore.headerStore}>
          <p>¿Cuál va a ser tu próximo nissan?</p>
        </div>
        <main className={stylesStore.mainStore}>
          <Container style={{ padding: '0 90px' }}>
            <Row xs={1} sm={1} md={2} lg={3} xl={3} className="g-3">
              {
                cars
                ? cars.results.map((elem, index) => {
                  const imgSrc = `https://s3.sa-east-1.amazonaws.com/simplimotos-stg.com/${elem.gallery[0].medium}`
                  const data =
                    <Col>
                        <div className={stylesCard.card}>
                          <img variant="top" src={imgSrc} className={stylesCard.cardImg}/>
                          <div className={stylesCard.cardBody}>
                            <h4 className={stylesCard.cardTitle}>{elem.model}</h4>
                            <div className={stylesCard.cardDivision}></div>
                            <div className={stylesCard.cardContentCenter}>
                              <div className="d-flex justify-content-between">
                                <div className="my-2 pr-0 d-flex align-items-center left-text-container">
                                  <div className="my-2 ml-auto justify-content-center align-self-center">
                                    <p className={stylesCard.cardLeftTextPrice}>PRECIO DESDE</p>
                                  </div>
                                </div>
                                <div className="my-2 ml-auto justify-content-center align-self-center">
                                  <p className={stylesCard.cardRightTextPrice}>{elem.detail.price.currency}$ {elem.detail.price.amount}</p>
                                </div>
                              </div>
                            </div>
                            <div className={stylesCard.cardDivision}></div>
                            <div>
                              <div className={stylesCard.cardContentDetails}>
                                <Link href="/store">
                                  <div className="d-flex justify-content-between">
                                    <a className={stylesCard.cardDetail}>VER DETALLES DE MODELO</a>
                                    <div className={stylesCard.cardArrowIcon}>
                                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                                      </svg>
                                    </div>
                                  </div>
                                </Link>
                              </div>
                              <p className={stylesCard.cardLeftText}>
                                Imágenes meramente ilustrativas no reportando la realidad exacta, pudiendo existir variaciones en la percepción.
                              </p>
                            </div>
                          </div>
                        </div>
                    </Col>
                  return data
                  })
                : <div>
                    <Spinner animation="border" role="status">
                      <span className="visually-hidden">Loading...</span>
                    </Spinner>
                  </div>
              }
            </Row>
            <p className={stylesStore.legalStore}>*Los precios expuestos en este catalogo son expresados en dólares americanos. Los mismos incluyen IVA y podrán variar en función al modelo y/o versión elegida. El precio por unidad reflejado en este catálogo refiere a la unidad de versión más económica por cada modelo. RALITOR SA se reserva el derecho de modificar y actualizar los mismos en cualquier momento. Es responsabilidad del cliente confirmar al momento de su compra, el precio final que aparece en el catálogo. No se incluyen Gastos de empadronamiento ni cualquier tipo de costo municipal, así como tampoco gastos de traslados, fletes o seguro del vehículo. No incluye costos de instalación de accesorios.</p>
          </Container>
        </main>
      </div>
      <Footer />
    </div>
  )
}
export async function getStaticProps(){
  try{
    const headers = {
      Authorization: "Bearer qwertyuiopasdfghjklzxcvbnm123456"
    }
    const res = await fetch("https://4my1q6hsyo.api.quickmocker.com/product", headers);
    const cars = await res.json();   
    return {
      props: {
        cars
      }
    }
  } catch (error) {
    console.log(error)
  }     
}